"""Initial migration after fixing owner relationship.

Revision ID: d5d759b75065
Revises: 
Create Date: 2024-09-18 11:35:29.111534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d759b75065'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('planet_type_id', sa.Integer(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('aluminium', sa.Float(), nullable=True),
    sa.Column('biomass', sa.Float(), nullable=True),
    sa.Column('crystals', sa.Float(), nullable=True),
    sa.Column('deuterium', sa.Float(), nullable=True),
    sa.Column('ferrite', sa.Float(), nullable=True),
    sa.Column('etereon', sa.Float(), nullable=True),
    sa.Column('gold', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_cap', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_planet_owner'),
    sa.ForeignKeyConstraint(['solar_system_id'], ['solar_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('starting_planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['starting_planet_id'], ['planet.id'], name='fk_user_starting_planet'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('population_assigned', sa.Integer(), nullable=True),
    sa.Column('is_under_construction', sa.Boolean(), nullable=True),
    sa.Column('construction_time_remaining', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('galaxy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['galaxy_id'], ['galaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ships', sa.PickleType(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('location_planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_type_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('population_assigned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('design', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solar_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_system')
    op.drop_table('ship')
    op.drop_table('research')
    op.drop_table('fleet')
    op.drop_table('cluster')
    op.drop_table('building')
    op.drop_table('user')
    op.drop_table('planet')
    op.drop_table('galaxy')
    # ### end Alembic commands ###
